Fix/various and tests
ITISFoundation/osparc-deployment-agent pull request #142
Opened 2023-02-08 19:13 UTC by mrnicegyu11

- Fixes system test on local machine
- Adds current version of portainer to integrations test
- More integrations tests for portainer
- Adds and tests REST DELETE stack route in portainer
- Various dependency updates
- Updates test's docker-compose file to current images for docker-registry unit test

2023-02-08 19:40 UTC, pcrespov requested changes

2023-02-08 19:40 UTC, pcrespov commented on .vscode/launch.json
> +    },
Version ``launch.json.template`` but unversion (ignore) ``launch.json``

2023-02-08 19:40 UTC, pcrespov commented on .vscode/launch.json
> +    },
This is the rule we use in .ignore
```.gitignore

# IDEs config (except templates)
.vscode/*
!.vscode/*.template.json
```

2023-02-08 19:40 UTC, pcrespov commented on tests/unit/test_portainer.py
> +    stack_name = "myAmazingstackname"
TIP: ``faker`` for fake values  https://faker.readthedocs.io/en/master/

```python
from faker import Faker


test_it(faker: Faker):
   swarm_id = faker.pyint(min=1)
   stack_name = faker.name()
  # ...
```

2023-02-23 15:38 UTC, mrnicegyu11 commented
THIS PR WAS SPLIT INTO 4 FOR BETTER READABILITY, SEE https://github.com/ITISFoundation/osparc-deployment-agent/pull/154

2023-02-23 15:38 UTC, closed without merging