Fix deployment agent failure when docker images cannot be fetched
ITISFoundation/osparc-deployment-agent pull request #44
Opened 2022-03-30 09:28 UTC by mrnicegyu11

## What do these changes do?

Fix a bug in the deployment agent, due to a type mismatch. This bug may occur when fetching docker images fails at one point in time, and then works again.

The most noticeable impact of this bug is that - if a mattermost client is configured - there will be erroneous mattermost notifications sent out every 3-5 minutes.

Bonus: Add test

Help with pytest by @GitHK is gratefully acknowledged.

## Checklist

- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes

2022-03-30 09:52 UTC, GitHK requested changes
Very nice overall.
Let's make it a bit better. Pleas split it up into two separate tests with appropriate names for what you are testing.
Advantages:
- simpler to read understand your intention
- simpler to debug and maintain

2022-03-30 09:52 UTC, GitHK commented on tests/unit/test_docker_registries_watcher.py
> +
I would create two new tests out of all the below

2022-03-30 09:52 UTC, GitHK commented on tests/unit/test_docker_registries_watcher.py
> +    )
I would put all this in a fixture

2022-03-30 09:52 UTC, GitHK commented on tests/unit/test_docker_registries_watcher.py
> +    mock_docker_client.return_value.images.get_registry_data.side_effect = None
here you would have a second fixture

2022-03-30 09:52 UTC, GitHK commented on tests/unit/test_docker_registries_watcher.py
> +    _assert_docker_client_calls(mock_docker_client, registry_config, valid_docker_stack)
and a second test

2022-03-30 09:52 UTC, GitHK commented on tests/unit/test_docker_registries_watcher.py
> +    _assert_docker_client_calls(mock_docker_client, registry_config, valid_docker_stack)
this would be your first test

2022-03-30 09:57 UTC, pcrespov approved these changes
Nice fix and even better test! Just some small suggestion about the test

2022-03-30 09:57 UTC, pcrespov commented on tests/unit/test_docker_registries_watcher.py
> +    # Handle the failure of fetching an image
very nice test!
Just a small suggestion:  i would create an independent test for this e.g. ``test_handle_failure_of_fetching_an_image``. It much better to have a lot of small unit tests with a very clear target than having one big-fat with a lot of checks and different contexts. If there are common parts, you can create helper functions or use the fixture.
Also mockups are typically part of the test setup, which is included in the fixture although when the test is small it is also acceptable to do it in the test-function body

2022-03-31 07:05 UTC, sanderegg approved these changes
great, I also agree that it would be nicer to have separate tests for separate issues (you could even put a link to the issue in the test)

2022-04-06 06:44 UTC, GitHK approved these changes
Looking better, thank!

2022-04-06 08:37 UTC, merged